version: "3.8"
services:
  server:
    container_name: server
    image: ping-pong:latest
    build: 
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    environment: 
      - server=http://127.0.0.1:5005
    command: ["main.py", "--host", "0.0.0.0", "--port", "5005", "--reload"]
  
  