apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-app
  template:
    metadata:
      labels:
        app: ansible-app
    spec:
      containers:
        - name: ansible-container
          image: finalproject_ansible-service_1
          ports:
            - containerPort: 5220
